// Generated by CoffeeScript 1.11.1
(function() {
  var app, bodyparser, express, http, metrics, user;

  http = require("http");

  express = require("express");

  bodyparser = require('body-parser');

  metrics = require("./metrics.coffee");

  user = require("./user.coffee");

  app = express();

  app.use(bodyparser.json());

  app.use(bodyparser.urlencoded());

  app.set('port', 1337);

  app.set('view engine', 'pug');

  app.set('views', __dirname + "/../views");

  app.use('/', express["static"](__dirname + "/../public"));

  app.get("/", function(req, res) {
    return res.render("index", {});
  });

  app.get("/hello/:name", function(req, res) {
    return res.render('hello', {
      name: req.params.name
    });
  });

  app.get("/metrics(/:id)?", function(req, res) {
    return metrics.get(req.params.id, function(err, value) {
      if (err) {
        throw next(err);
      }
      return res.status(200).json(value);
    });
  });

  app.post("/metrics/:id", function(req, res) {
    return metrics.put(req.params.id, req.body, function(err) {
      if (err) {
        throw next(err);
      }
      return res.status(200).send();
    });
  });

  app["delete"]("/metrics/:id", function(req, res) {
    return metrics.remove(req.params.id, function(ok) {
      if (ok) {
        return res.status(200).send();
      } else {
        return res.status(404).send();
      }
    });
  });

  app.listen(app.get('port'), function() {
    return console.log("listening on port " + (app.get('port')));
  });

}).call(this);
