// Generated by CoffeeScript 1.11.1
(function() {
  var db;

  db = require("./db")(__dirname + "/../db/user-metric");

  module.exports = {

    /*
      'get(username, callback)'
      ----------------------
      Parameters
      'username'  Username
      'callback'  Callback function
     */
    get: function(username, callback) {
      var metricsId, rs;
      metricsId = [];
      rs = db.createReadStream();
      rs.on("data", function(data) {
        var _, _userMetricId, _username, ref;
        ref = data.key.split(":"), _ = ref[0], _username = ref[1], _userMetricId = ref[2];
        if (data.value && _username === username) {
          return metricsId.push(_userMetricId);
        }
      });
      rs.on("error", callback);
      return rs.on("close", function() {
        return callback(null, metricsId);
      });
    },

    /*
      'save(username, mId, callback)'
      ----------------------
      Parameters
      'username'  Username
      'mId'       Id metric
      'callback'  Callback function
     */
    save: function(username, mId, callback) {
      var i, len, m, ws;
      ws = db.createWriteStream();
      ws.on("error", callback);
      ws.on("close", callback);
      for (i = 0, len = mId.length; i < len; i++) {
        m = mId[i];
        ws.write({
          key: "user-metric:" + username + ":" + m,
          value: true
        });
      }
      return ws.end();
    },

    /*
      'remove(username, mId, callback)'
      ----------------------
      Parameters
      'username'  Username
      'mId'       Id metric
      'callback'  Callback function
     */
    remove: function(username, mId, callback) {
      return db.del("user-metric:" + username + ":" + mId, function(err) {
        return callback(err);
      });
    }
  };

}).call(this);
