// Generated by CoffeeScript 1.11.1
(function() {
  var express, router, user;

  user = require("../user");

  express = require("express");

  router = express.Router();

  router.get("/signup", function(req, res) {
    return res.render("signup");
  });

  router.get("/signin", function(req, res) {
    return res.render("signin");
  });

  router.get("/signout", function(req, res) {
    req.session.signIn = false;
    delete req.session.username;
    return res.redirect("/signin");
  });

  router.post("/signup", function(req, res) {
    return user.save(req.body.username, req.body.password, function(err, value) {
      if (err) {
        return res.redirect("/signup");
      } else {
        return res.redirect("/hello/" + req.body.username);
      }
    });
  });

  router.post("/signin", function(req, res) {
    return user.get(req.body.username, function(err, data) {
      if (err) {
        res.redirect("/signin");
      }
      if (!data.username) {
        return res.redirect("/signin");
      } else if (data.pwd !== req.body.password) {
        return res.redirect("/signin");
      } else {
        req.session.signIn = true;
        req.session.username = data.username;
        return res.redirect("/hello/" + req.body.username);
      }
    });
  });

  module.exports = router;

}).call(this);
