// Generated by CoffeeScript 1.11.1
(function() {
  var express, metrics, router, user, userMetric;

  metrics = require("../metrics");

  user = require("../user");

  userMetric = require("../user-metric");

  express = require("express");

  router = express.Router();

  router.get("/", function(req, res) {
    if (!req.session) {
      return res.redirect("/signin");
    } else {
      return res.redirect("/hello/" + req.session.username);
    }
  });

  router.get("/user/:username", function(req, res) {
    return user.get(req.params.username, function(err, value) {
      if (err) {
        return res.status(404).send(err);
      } else {
        return res.status(200).json(value);
      }
    });
  });

  router.get("/hello/:name", function(req, res) {
    return res.render("hello", {
      name: req.params.name
    });
  });

  router["delete"]("/user/:username", function(req, res) {
    return user.remove(req.params.username, function(err) {
      if (err) {
        return res.status(404).send(err);
      } else {
        return res.status(200).send();
      }
    });
  });

  module.exports = router;

}).call(this);
